apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-aggregation-service
  namespace: nimble-platform
  labels:
    app: nimble-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-aggregation-service
  template:
    metadata:
      labels:
        app: data-aggregation-service
    spec:
      containers:
        - name: data-aggregation-service
          image: 'rannybal2024/data-aggregation-service:IMAGE_TAG'
          ports:
            - containerPort: 9100
              protocol: TCP
          resources:
            limits:
              memory: 2000Mi
              cpu: 800m
            requests:
              cpu: 200m
              memory: 256Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600